config/routes.rb
Rails.application.routes.draw do
  resources :queries
  get 'pages/home' => 'pages#home'
  get 'apiquery' => 'queries#apiquery'
  root 'queries#index'
  get 'dashboard' => 'pages#dashboard'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/query.rb
class Query < ApplicationRecord

  validates :tweet_sum, presence: true
  validates :retweet_sum, presence: true
  validates :exposure_sum, presence: true
  validates :hashtag, presence: true

  # Retrieve JSON response based on user input.
  def self.api_response(term)
    url = "https://api.ritekit.com/v1/stats/history/#{term}?tags=&client_id="
    api = '38eae4081cf927bfba61c378a89dc3cd820c8696b5dd'
    HTTParty.get(url + api)
  end

  # Format raw numerical sum value.
  def format_results(value)
      value = value.to_i
      
      if  value == 0
        return "N/A"
      end
      
      if value > 1000 && value < 1000000
        result = value / 1000
        result = '%.1f' % result
        return result.to_s + 'K'
      end

      if value > 1000000 && value < 1000000000
        result = value / 1000000
        result = '%.1f' % result
        return result.to_s + 'M'
      end

      if value > 1000000 && value < 100000000000
        result = value / 1000000000
        result = '%.1f' % result
        return result.to_s + 'B'
      end

      if value < 1000 && value > 0
        return value.to_s
      end

    
  end
  
  def not_available(value)
    if value.nil?
      return 'N/A'
    else
      return value
    end
  end
  
  def value_less_than_1000(value)
    if value < 1000 && value > 0
      return value.to_s
    end
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :queries
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]


  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session['devise.facebook_data'] && session['devise.facebook_data']['extra']['raw_info']
        user.email = data['email'] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name # assuming the user model has a name
      user.image = auth.info.image.gsub('http://', 'https://')
    end
  end

  def largeimage
    "http://graph.facebook.com/#{uid}/picture?type=large"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!

  def dashboard
    @queries = Query.all
  end

end

app/controllers/queries_controller.rb
class QueriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @queries = Query.all
  end

  def apiquery
    search_term = params[:query]
    if search_term.present?
      @stats = Query.api_response(search_term)
    end

    respond_to do |format|
      format.js
      format.html
    end
  end

  def create
    @query = Query.create(queries_params)

    @query.save
    redirect_to root_path
  end

  private

  def queries_params
    params.require(:query).permit(:time, :tweet_sum,
                   :retweet_sum, :exposure_sum, :hashtag)
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

    def facebook
      @user = User.from_omniauth(request.env["omniauth.auth"])

      if @user.persisted?
        sign_in_and_redirect @user, :event => :authentication
        set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
      else
        session["devise.facebook_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
    end

    def failure
      redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    
    def user_params
        params.require(:first_name, :last_name).permit(:email, :password, :password_confirmation, :remember_me, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/queries_helper.rb
module QueriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.js"></script>
		<script src="https://cdn.datatables.net/plug-ins/1.10.19/api/sum().js"></script>
		<link href="https://fonts.googleapis.com/css?family=Righteous" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Montserrat:400,800" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Audiowide" rel="stylesheet">
   <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
  </head>

  <%= render 'shared/nav' %>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>


    <%= yield %>

  </body>

</html>

app/views/pages/apiquery.js.erb
if ( ! $.fn.DataTable.isDataTable( '#main-results' ) ) {
  $('#main-results').DataTable({

    "data": gon.queries['data'],
	
  "columns": [
      {   
        "data": "date",
  	  render: function( value, type, row ) {
  	      return formatDate(value);
  	  }
	},
	{
	  "data": "retweets",
	   render: function( data, type, row ) {
	      return formatResults( data );
	  }
	},
	{
	  "data": "tweets",
	   render: function( data, type, row ) {
  	     return formatResults( data );
	   }
	},
	{
      "data": "exposure",
      render: function( data, type, row ) {
         return formatResults( data );
      }
	}
  ]
});
} 

function currentTime() {
    var time = new Date();
    return time.getHours() + ':' + time.getMinutes();
}

function formatResults(value) {
    let result;
    
    if ( value == 0 || value == null || value == undefined || value == '') {
        return "N/A";
    }
   
    if ( value < 1000 && value > 0) {
	    return value;
    }
    
    if ( value > 1000 && value < 1000000 ) {
        result = value / 1000;
        return result.toFixed(1) + 'K';
    }
    
    if ( value > 1000000 ) {
        result = value / 1000000;
        return result.toFixed(1) + "M";
    }
  
    if ( value < 1000 && value > 0) {
        return value;
    }
    
}



function tweetsSum() {
  var table = $('#main-results').DataTable();
  return table.column( 1 ).data().sum();
}

function retweetsSum() {
  var table = $('#main-results').DataTable();
  return table.column( 2 ).data().sum();
}

function exposureSum() {
  var table = $('#main-results').DataTable();
  return table.column( 3 ).data().sum();
}

function formatDate(dateValue) {
    var months = ['Jan', 'Feb', 'Mar', 'Apr',
  		  'May', 'Jun', 'Jul', 'Aug',
  		  'Sept', 'Oct', 'Nov', 'Dec'];
  		          
    var date2 = new Date(dateValue);
    return months[ date2.getMonth() ] + " " + date2.getDate() +
          ", " + date2.getFullYear();
}

app/views/pages/dashboard.html.erb
<div class="queries-section">

    <% @queries.each do |m| %>
        <div class='query-box'>
            <p class='time-ago'><%= m.created_at %> </p><br><br>
            <% if m.hashtag == nil %>
                 <p class='user-sum'><b>Hashtag: </b><span class='sum-value'><%= m.hashtag %></span></p>
            <% else %>
                <p class='user-sum'>Hashtag: <span class='sum-value'><%= m.hashtag %></span></p>
            <% end %>
            <p class='user-sum'><b>Tweet: </b><span class='sum-value'><%= m.format_results(m.tweet_sum) %></span></p>
            <p class='user-sum'><b>Retweets: </b><span class='sum-value'><%= m.format_results(m.retweet_sum) %></span></p>
            <p class='user-sum'><b>Exposure: </b><span class='sum-value'><%= m.format_results(m.exposure_sum) %></span></p>
        </div>
    <% end %>
    
</div>

app/views/queries/apiquery.js.erb
$(document).ready(function(){
  var stats = <%= raw @stats.to_json %>
  hashValue(stats)
  showTables();
  generateTable(stats);
  generateSummaryTable(stats);
});

// Generates summary table
const generateSummaryTable = (stats) => {
  hashTerm(stats);
  appendTweetsSum();
  appendRetweetsSum();
  appendExposureSum();
  information();
}

// Creates a HTML element with provided element
const createElements = (element) => {
  return document.createElement(element);
}

// Creates a node of text
const createNode = (text) => {
  return document.createTextNode(text);
}

// Set class to element
const setClass = (nodeElement, classname) => {
  nodeElement.className = classname;
}

// Appends sum of Exposure
const appendExposureSum = () => {
  return appendItems('p', 'hash-sum', 'Ex', exposureSum());
}

// Appends sum of Retweets
const appendRetweetsSum = () => {
  return appendItems('p', 'hash-sum', 'Rt', retweetsSum());
}

// Appends sum of Tweets
const appendTweetsSum = () => {
  return appendItems('p', 'hash-sum', 'Tw', tweetsSum());
}

// Display value with one number after decimal
const oneDecimal = (result, value) => {
  return result.toFixed(1) + value;
}

// Search term provided by user
const hashValue = (stats) => {
    return stats.hashtag;
}

// Display table
const showTables = () => {
  $(".results-area").show();
  $('#summary').show();
}

// Format current time
const currentTime = () => {
    var time = new Date();
    return time.getHours() + ':' + time.getMinutes();
}

// Get sum of retweet column
const tweetsSum = () => {
    var table = $('#tag-history-table').DataTable();
    return sumOfColumn(table, 1);
}

// Get sum of retweet column
const retweetsSum = () => {
    var table = $('#tag-history-table').DataTable();
    return sumOfColumn(table, 2);
}

// Get sum of exposure column
const exposureSum = () => {
    var table = $('#tag-history-table').DataTable();
    return sumOfColumn(table, 3);
}

// Get sum of column
const sumOfColumn = (table, value) => {
  return table.column(value).data().sum()
}

const validateData = (data) => {
  let result;
  formatResults(data) === undefined ?
  result = 'N/A' : result = formatResults(data)
  return result;
}

// Format date
const formatDate = (dateValue) => {
    var months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug',
  		          'Sept', 'Oct', 'Nov', 'Dec'];

    var date2 = new Date(dateValue);
    return months[ date2.getMonth() ] + " " + date2.getDate() +
          ", " + date2.getFullYear();
}

// Displays message in the summary box
const information = () => {
  const nodeElement = createElements('p')
  const textForParagraph = createNode(
    "Results show total sums of uses for this hashtag in the past 30 days."
  );
  setClass(nodeElement, 'information');
  nodeElement.appendChild(textForParagraph);
  document.getElementById('summary').appendChild(nodeElement);
}

// Appends given items to DOM element
const appendItems = (element, classNames, acro, type) => {
  var newParagraph = createElements(element);
  var img = new Image();
  img.src = "assets/megaphone.png"
  setClass(newParagraph, classNames);
  var textForParagraph = createNode(formatResults(type));
  newParagraph.appendChild(img)
  newParagraph.appendChild(textForParagraph);

  document.getElementById('summary').appendChild(newParagraph);
}

// Appends hash search value to element
const hashTerm = (data) => {
  var newParagraph = createElements("p");
  setClass(newParagraph, 'hash-term');
  var textForParagraph = createNode('#' + data['hashtag']);
  newParagraph.appendChild(textForParagraph);
  document.getElementById('summary').appendChild(newParagraph)
}

// Submit user query result to database
const ajaxRequest = (data) => {
  return $.ajax({
          type: 'POST',
          url: "/queries",
          data: {
            query: {
              hashtag: hashValue(data),
              tweet_sum: tweetsSum(),
              retweet_sum: retweetsSum(),
              exposure_sum: exposureSum()
            }
          }
        })
}

// Generate table
const generateTable = (data) => {
    if ( ! $.fn.DataTable.isDataTable( '#tag-history-table' ) ) {
        $('#tag-history-table').DataTable({
        "searching": false,
        "responsive": true,
        "drawCallback": () => {
            ajaxRequest(data)
          },
          "data": data.data,
          "columns": [
            {
              "data": "date",
        	     render: ( value, type, row ) => {
                  return formatDate(value);
        	     }
          	},
          	{
          	  "data": "retweets",
          	   render: ( data, type, row ) => {
                 return validateData(data);
          	   }
          	},
          	{
          	  "data": "tweets",
          	   render: ( data, type, row ) => {
                 return validateData(data);
          	   }
          	},
          	{
              "data": "exposure",
              render: ( data, type, row ) => {
                return validateData(data)
              }
          	}
          ]
        });
    }
}

// Format results
const formatResults = (value) => {
  console.log(value)
    let result;

    if ( value == 0 || value == null || value == undefined || value == '') {
        return "N/A";
    }

    if ( value < 1000 && value > 0) {
	    return value;
    }

    if ( value > 1000 && value < 1000000 ) {
        result = value / 1000;
        return oneDecimal(result, 'K');
    }

    if ( value > 1000000 && value < 1000000000 ) {
        result = value / 1000000;
        return oneDecimal(result, 'M');
    }
  
    if ( value > 100000000 && value < 100000000000 ) {
        result = value / 1000000000;
        return oneDecimal(result, 'B');
    }

    if ( value < 1000 && value > 0) {
        return value;
    }
}

app/views/queries/index.html.erb
<main>
    <header>
        <h1 class='sub-logo'>#HashTaggedIt</h1>
    </header>

    <section>
        <p class='hashtag-prompt'>
            Enter a hashtag to find it's 30 day history
        </p>
        <div id='hashtag-query-form'>
            <%= render 'shared/form' %>
        </div>
    </section>

    <!-- Display's summary of table results -->
    <div id='summary'></div>

    <div class='results-area'>
        <!-- Display JSON values in DataTables -->
        <div class='table-responsive'>
          <table id='tag-history-table' class='display' cellspacing='0' width='100%'>
              <thead>
                  <tr>
                      <th>Date</th>
                      <th>Retweets</th>
                      <th>Tweets</th>
                      <th>Exposure</th>
                  </tr>
              </thead>
          </table>
        </div>
     </div>
</main>

app/views/queries/index.js.erb
$(document).ready(function(){
    var stats = <%= raw @stats.to_json %>
    showHistoryTable();
    generateTable(stats.data);
    hashTerm(stats);
    appendTweetsSum();
    appendRetweetsSum();
    appendExposureSum();
    information();
});

function information() {
    var newParagraph = document.createElement("p");
    newParagraph.className = 'information';
    var textForParagraph = document.createTextNode('Results show total sums of uses for this hashtag in the past 30 days.');
    newParagraph.appendChild(textForParagraph);
    document.getElementById('summary').appendChild(newParagraph) 
}

function hashTerm(data) {
    var newParagraph = document.createElement("p");
    newParagraph.className = 'hash-term';
    var textForParagraph = document.createTextNode('#' + data['hashtag']);
    newParagraph.appendChild(textForParagraph);
    document.getElementById('summary').appendChild(newParagraph)
    data['hashtag'];
}

function appendExposureSum () {
    var newParagraph = document.createElement("p");
    newParagraph.className = 'hash-sum';
    var textForParagraph = document.createTextNode('Ex: ' + formatResults(exposureSum()));
    newParagraph.appendChild(textForParagraph);
    document.getElementById('summary').appendChild(newParagraph) 
}

function appendRetweetsSum() {
    var newParagraph = document.createElement("p");
    newParagraph.className = 'hash-sum';
    var textForParagraph = document.createTextNode('Rt: ' + formatResults(retweetsSum()));
    newParagraph.appendChild(textForParagraph);
    document.getElementById('summary').appendChild(newParagraph)  
}

function appendTweetsSum() {
    var newParagraph = document.createElement("p");
    newParagraph.className = 'hash-sum';
    var textForParagraph = document.createTextNode('Tw: ' + formatResults(tweetsSum()));
    newParagraph.appendChild(textForParagraph);
    document.getElementById('summary').appendChild(newParagraph)
}

function generateTable(data) {

    if ( ! $.fn.DataTable.isDataTable( '#tag-history-table' ) ) {
        $('#tag-history-table').DataTable({
        
        "searching": false,
        "data": data,
        "columns": [
            {
              "data": "date",
        	  render: function( value, type, row ) {
        	      return formatDate(value);
        	  }
          	},
          	{
          	  "data": "retweets",
          	   render: function( data, type, row ) {
          	      return formatResults( data );
          	  }
          	},
          	{
          	  "data": "tweets",
          	   render: function( data, type, row ) {
            	     return formatResults( data );
          	   }
          	},
          	{
                "data": "exposure",
                render: function( data, type, row ) {
                  return formatResults( data );
                }
          	}
          ]
        });
    }
}

function formatResults(value) {
    let result;
    
    if ( value == 0 || value == null || value == undefined || value == '') {
        return "N/A";
    }
   
    if ( value < 1000 && value > 0) {
	    return value;
    }
    
    if ( value > 1000 && value < 1000000 ) {
        result = value / 1000;
        return result.toFixed(1) + 'K';
    }
    
    if ( value > 1000000 && value < 1000000000 ) {
        result = value / 1000000;
        return result.toFixed(1) + "M";
    }
    
    if ( value > 100000000 && value < 100000000000 ) {
        result = value / 1000000000;
        return result.toFixed(1) + "B";
    }
    
    
    if ( value < 1000 && value > 0) {
        return value;
    }
    
}

function showHistoryTable() {
    $(".results-area").show();
    $('#summary').show();
}

function currentTime() {
    var time = new Date();
    return time.getHours() + ':' + time.getMinutes();
}

function tweetsSum() {
    var table = $('#tag-history-table').DataTable();
    return table.column( 1 ).data().sum();
}

function retweetsSum() {
    var table = $('#tag-history-table').DataTable();
    return table.column( 2 ).data().sum();
}

function exposureSum() {
    var table = $('#tag-history-table').DataTable();
    return table.column( 3 ).data().sum();
}

function formatDate(dateValue) {
    var months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug',
  		          'Sept', 'Oct', 'Nov', 'Dec'];
  		          
    var date2 = new Date(dateValue);
    return months[ date2.getMonth() ] + " " + date2.getDate() +
          ", " + date2.getFullYear();
}

app/views/shared/_form.html.erb
<%= form_tag apiquery_path, method: :get, remote: true do %>
    <%= text_field_tag :query, params[:query], placeholder: 'Type in hashtag here', class: 'hashtag-form' %><br>
    <%= submit_tag 'Search', class: 'submit' %>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-dark bg-dark navbar-expand-lg navbar-light bg-light">

  <%= link_to image_tag('hashtag-logo'), root_path, class: 'logo' %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto main-nav">
      <% if user_signed_in? %>
        <% if current_user.image %>
          <li class='nav-item'><%= image_tag current_user.image, class: 'avatar' %></li>
        <% end %>
        <li class='nav-item logout'><%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'nav-link' %></li>
        <li class='nav-item dashboard'><%= link_to "Dashboard", dashboard_path, class: 'nav-link' %></li>
      <% else %>
        <li class='nav-item session'><%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %></li>
      <% end %>
    </ul>
  </div>
</nav>